# Generated by Django 3.1.5 on 2021-07-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fball_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='FTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fball_calculator.team'),
        ),
    ]
